[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
simple_stake = "4EWZ9ERDuq1tQ41XoghKgTuwvotL5p3VrzUaXgrsGfvs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/muhammad/wallet/keypair1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
